name: Create automatic Pull Request

on:
  push:
    branches:
      - main
      - master
    
jobs:
  AutomaticPR:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v4

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

     # - name: Update author information
      #  run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR 1
        id: test-1
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "branchcreate"
          base: master
          title: "Demo for auto pr1"
        #  committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
        #  author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          #delete-branch: true
      - name: Pull request number
        run: |
          echo "Pull Request Number - ${{ steps.test-1.outputs.pull-request-number }}"
      #- name: Merge request     
       # uses: davideviolante/pr-automerge-action@v1.3.3
       # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
         # merge-method: 'squash' # Default 'squash'
         # min-approvals: 1 # Default 2
         # base-ref: 'master' # Default 'master'

